spring:
  datasource: 
    username: root
    password: Cva@@51235213
    url: jdbc:mysql://localhost:3306/PROJECTUSER3_MASTER
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
planapi:
  messages:
    planSaveSucc: Plan Saved Successfully
    planSaveFail: Plan Save Failed
    planUpdateSucc: Plan Updated Successfully
    planUpdateFail: Plan Failed to Update
    planDeleteSucc: Plan Deleted Successfully
    planDeleteFail: Plan Failed to Delete
    planStatusChange: Plan Status Changed Successfully
    planStatusChangeFail: Plan Status Change Failed
server:
  port: 8080